# Generated by Django 6.0.2 on 2026-03-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='price_paid',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
